---
abstract: 'Perl extension for representing and manipulating MAC addresses '
author:
  - 'Karl Ward <karlward@cpan.org>'
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-MAC
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.1
version: 1.5
